name: Daily NSE Data Update and Plot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1-5'  # Runs at 8:30 AM IST (3:00 AM UTC) Monday to Friday

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run scraper script
      run: python nse_scraper.py

    - name: Run plot script
      run: python plot_graphs.py

    - name: Upload output plots
      uses: actions/upload-artifact@v3
      with:
        name: plot-outputs
        path: outputs/
