name: Daily NSE Data Update and Plot

on:
  schedule:
    - cron: '30 13 * * *'  # Runs at 6:30 PM IST (13:30 UTC)
  workflow_dispatch:       # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run data fetch
        run: python main.py

      - name: Run graph plots
        run: python plot_graphs.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "📊 Daily auto-update: $(date +'%Y-%m-%d')"
          git push
